(source "gnu" "https://elpa.zilongshanren.com/gnu/")
(source "melpa" "https://elpa.zilongshanren.com/melpa/")
(source "melpa-stable" "https://elpa.zilongshanren.com/melpa-stable/")

(depends-on "company")
(depends-on "counsel")
(depends-on "cyberpunk-theme")
(depends-on "hungry-delete")
(depends-on "magit")
(depends-on "monokai-theme")
(depends-on "pallet")
(depends-on "powerline")
(depends-on "smartparens")
(depends-on "swiper")
(depends-on "use-package")
(depends-on "dash")
