(source "gnu" "https://elpa.zilongshanren.com/gnu/")
(source "melpa" "https://elpa.zilongshanren.com/melpa/")
(source "melpa-stable" "https://elpa.zilongshanren.com/melpa-stable/")

(depends-on "ace-window")
(depends-on "avy")
(depends-on "base16-theme")
(depends-on "beacon")
(depends-on "clipmon")
(depends-on "company")
(depends-on "company-emacs-eclim")
(depends-on "counsel")
(depends-on "cyberpunk-theme")
(depends-on "dash")
(depends-on "diminish")
(depends-on "eclim")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "goto-last-change")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-core")
(depends-on "helm-projectile")
(depends-on "hungry-delete")
(depends-on "ivy")
(depends-on "ivy-hydra")
(depends-on "magit")
(depends-on "monokai-theme")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "powerline")
(depends-on "smartparens")
(depends-on "spaceline")
(depends-on "super-save")
(depends-on "swiper")
(depends-on "use-package")
(depends-on "vimish-fold")
(depends-on "which-key")
